### ISSUE TITLE
CRs lack "status" field

### ISSUE THREAD

**Issue by fromanirh** [MarSik/kubevirt-ssp-operator#28]
We need to add "status" fields to express installation status of CRs.

Additionally: in the current form, the operator is likely trying to (re)deploy CRs every iteration. We need to check this. If so, the "status" field can prevent that.

**Comment by MarSik** [comment]
We do have status in all the CRDs

https://github.com/MarSik/kubevirt-ssp-operator/blob/master/deploy/crds/kubevirt_v1_commontemplatesbundle_crd.yaml#L15
https://github.com/MarSik/kubevirt-ssp-operator/blob/master/deploy/crds/kubevirt_v1_nodelabellerbundle_crd.yaml#L15
https://github.com/MarSik/kubevirt-ssp-operator/blob/master/deploy/crds/kubevirt_v1_templatevalidator_crd.yaml#L15

There indeed is a possible bug with the playbooks running in loop even though nothing has changed. We should be able to fix that by setting the reconcilePeriod: 0 in the watches.yaml

https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/advanced_options.md#watches-file-options

**Comment by fromanirh** [comment]
Ack. However we have multiple reports of the operator repeatedly running roles and attempting to (re)install the components. So far no issues reported because k8s/ocp handles this nicely behind the curtains, so it is "just" wated work.
We should look into this.

**Comment by fromanirh** [comment]
No longer relevant. Fixed in versions v1.0.8 and v1.0.9
