### ISSUE TITLE
pluggable defaults.yml

### ISSUE THREAD

**Issue by fromanirh** [MarSik/kubevirt-ssp-operator#41]
It feels very awkward to be force to rebuild the container image for each dependency bump.
I'd like to have a mechanism (e.g. a ConfigMap)? to update the dependency list at runtime.

Expected flow:
- urgent fixes could be delivered using *either* a new image or an update dependencies map
- at consistent but slower pace, the base dependency map is updated and the new container image always contain the freshest at build time

**Comment by MarSik** [comment]
I think this might be possible already. The ansible operator base image supports some environment variables. I am aware of ANSIBLE_VERBOSITY, but there might be more and one way to override variables is to specify new values on command line. I will try to check this with the operator team.

**Comment by MarSik** [comment]
It might be possible to mount a configmap or secret to `/etc/ansible/facts.d/<whatever>.fact`. Ansible should pick that up automatically. Then we could try redefining the variables that control the versions.

**Comment by MarSik** [comment]
Hmm it won't work. The variable precedence is wrong. The only way to override playbook vars is --extra-vars command line option and it does seem to have env var equivalent

**Comment by MarSik** [comment]
But we could mount a file (config map, secret) that overrides the _defaults.yml file we already have. And that should work just fine.

**Comment by fromanirh** [comment]
After some discussion, this whole issue/RFE seems at odds with the goal of kubevirt core to know exactly what's running inside a cluster at any given time.
