### ISSUE TITLE
Operator deploys old version of template validator

### ISSUE THREAD

**Issue by ksimon1** [MarSik/kubevirt-ssp-operator#63]
Due to version specified in https://github.com/MarSik/kubevirt-ssp-operator/blob/master/deploy/crds/kubevirt_v1_templatevalidator_cr.yaml#L7 operator deploys old version of template validator (it overrides correct variable in _defaults.yml file)

/cc @fromanirh, @MarSik

**Comment by fromanirh** [comment]
It works with HCO because HCO doesn't specifiy the version. So this affects only the standalone deployments of our operator. Nevertheless, it's a bug. Good catch Karel!

**Comment by ksimon1** [comment]
Closing, as this issue is already fixed by https://github.com/MarSik/kubevirt-ssp-operator/pull/92
